### ISSUE TITLE
Allow pass to `QModelMenu` constructor  dict with mapping from types to instances

### ISSUE THREAD

**Issue by Czaki** [pyapp-kit/app-model#176]
To avoid depending on injection resolving on menu clicking (see https://github.com/napari/napari/issues/6466) it will be nice to allow providing mapping (like `{Viever: viever_instance}`) to `QModelMenu`. As `QModelMenu`  is often glued to a given window, it will not provide any risk, but reduce error probability. 

The items passed in dict should be stored as weakref internally and unwrapped on trigger fire.

**Comment by lucyleeow** [comment]
@DragaDoncila and I had a look at how this could be implemented but are a bit stumped.

Binding a window to a `QModelMenu` instance is easy enough but it's not clear how best to pass this to an action execution, when the action was executed from a menu.

Ideally we would do this at `execute_command` inside `_on_triggered` [here](https://github.com/pyapp-kit/app-model/blob/a0c33c36dcf9dd2cc9bfd70ab5c4440c74e0f8b2/src/app_model/backends/qt/_qaction.py#L55). But at this step we have no context about where the call came from. I'm also unsure of how best to pass the bound object to `Store.inject`.

A ugly way that could work would be to create a different `QMenuItemAction` in [`_rebuild`](https://github.com/pyapp-kit/app-model/blob/a0c33c36dcf9dd2cc9bfd70ab5c4440c74e0f8b2/src/app_model/backends/qt/_qmenu.py#L300), so that the action that is added to menus, has a callback with the bound argument. I think this would involve making a whole new `CommandRule` though.

Suggestions welcome.

**Comment by Czaki** [comment]
The `QMenuItemAction` 
https://github.com/pyapp-kit/app-model/blob/a0c33c36dcf9dd2cc9bfd70ab5c4440c74e0f8b2/src/app_model/backends/qt/_qaction.py#L118

know its context, as parent menu is passed during creation, 

https://github.com/pyapp-kit/app-model/blob/a0c33c36dcf9dd2cc9bfd70ab5c4440c74e0f8b2/src/app_model/backends/qt/_qmenu.py#L323

so we could reimplement `_on_triggered` in this class.

**Comment by tlambert03** [comment]
i don't yet have strong opinions on this either way, but just for the sake of discussion, can we "motivate" this change a bit more please?

from a straight reading of this issue, the primary napari issue linked is https://github.com/napari/napari/issues/6466, which was then closed by https://github.com/napari/napari/pull/6468 ... while I don't doubt that injection ended up being "involved" in that stack trace, a "naive" reading of those issues seems more to be that napari still has a number of "tightly coupled" things that must happen in just the right order to avoid bugs (this has always been the case, and as you all know, it's an ongoing bit of work to kinda "unspaghetti" the codebase).

> As QModelMenu is often glued to a given window, it will not provide any risk, but reduce error probability.

this statement does make sense to me from a Qt perspective, but i'm not immediately convinced that the solution needs to be that we allow *non* qt objects (like `napari.Viewer`) to be bound to QModelMenu commands.  If we were strictly trying to solve this particular statement, shouldn't a QModelMenu know which QWindow it belongs to?  That is, isn't it a little bit circuitous, and perhaps specific to napari's case, to say "here's the `napari.Viewer` object which this QModelMenu will be bound to... yes, that napari.Viewer will only have a single QMainWindow, and yes that QMainWindow will also necessarily be the parent of this QModelMenu, but don't worry about that, i still want to give you this object"


I don't doubt that I've missed some subtlety of the case here, but I wonder if this has moved directly to the implementation phase without more deeply discussing whether the proposed approach is really the best way to solve whatever issues motivated this in the first place?

**Comment by tlambert03** [comment]
Im going to close this.  It's a subset of #52 and not the way I want to see the solution implemented.

I _can_ imagine a better way to retrieve parents of objects in tree-like structures... but it's not going to be by passing a literal dict of injection kwargs into the QMenu
