### ISSUE TITLE
How do I use `Expr.in_`?

### ISSUE THREAD

**Issue by hanjinliu** [pyapp-kit/app-model#201]
* app-model version: 0.2.7
* Python version: 3.11.9
* Operating System: Windows 11

### Description

The `in_` method seems not working with a constant list. 
What I wanted to do was to use a ContextNamespace `ctx` and make a enablement statement like `ctx.window_state.in_(["minimized", "maximized"])`. I think I can make it work by defining another ContextKey that always returns a constant list, but I think there should be some easier way to do that.

### What I Did

```
expr = Constant(1).in_(Constant(2))  # <- not working, as a constant is not iterable
expr = Constant(1).in_([1, 2])  # <- not working, as a list is not a constant
expr = Constant(1).in_(ast.List(1, 2))  # <- not working, as a ast.List is not a constant
```

**Comment by tlambert03** [comment]
might need to see more to help you with your example... but I'm not sure you're thinking about the in_ operator on Expression instance correctly.  two observations:
1. `in_` the argument passed to `in_` must be either an `Expr` or anything that can be easily cast to an `Expr`.  So, actually, your first example *does* work fine (in the sense that it's not an exception), but when you try to evaluate it, it's meaningless (because the statement `1 in 2` doesn't make sense)
    ```python
    In [20]: Constant(1).in_(Constant(2))
    Out[20]: Expr.parse('1 in 2')
    ```

2.   usually, you would build and evaluate an expression like this:
```python
from app_model.expressions import parse_expression

expr = parse_expression('1 in some_list')

# and then later evaluate it
expr.eval({'some_list': [1, 2]})  # True
```

so, help me understand your intentions here?  What are you trying to check?  `ctx.window_state.in_(["minimized", "maximized"])` suggests you want an expression that returns true if the window state is *either* minimized or maximized?

**Comment by hanjinliu** [comment]
Hi @tlambert03 , thanks for your reply.

Sorry my question was not specific.
I want to use `QModelMainWindow` and `Action` to simplify the logic of enabling/disabling menu items according to the application state, such as the window state. Every time the window state changes, the context key `ctx.window_state` will be updated (to "normal", "minimized", "maximized" or "full") and the context of the menubar will be updated as well. 
If I need an `Action` that will only be enabled when the window is either minimized or maximized, I'll want to define an `Action` like:

```python
Action(
    id="my-action",
    ...,  # other arguments
    enablement=ctx.window_state.in_(["minimized", "maximized"]),
)
```

but I could not find a way to use `in_` in the enablement argument. As `Expr._cast` only allows `Expr` or `Constant`, maybe a class that inherits both `Expr` and `ast.List` is needed for this purpose?

**Comment by hanjinliu** [comment]
Thank you for the the explanation and the quick PR! I understand there might be some potential risks with more grammars. For my use case, I think joining equalities is fine.
