### ISSUE TITLE
How to specify button type in `QModelToolBar`?

### ISSUE THREAD

**Issue by lucyleeow** [pyapp-kit/app-model#204]
### Description

Is it possible to specify button type (e.g., `qtpy.QtWidgets.QRadioButton`, `napari._qt.widgets.qt_mode_buttons.QtModeRadioButton` etc) for actions inside a `QModelToolBar`?

Looking at `Action` it seems that the fields are fairly menu specific?

Context:

We are looking at migrating the viewer buttons and [layer controls](https://github.com/napari/napari/tree/2e9b117a80a43af144457c83f599ffa5bae684a7/napari/_qt/layer_controls) in napari to app-model.

**Comment by lucyleeow** [comment]
cc @dragadoncila

**Comment by tlambert03** [comment]
> Looking at Action it seems that the fields are fairly menu specific?

A [QToolbar](https://doc.qt.io/qt-6/qtoolbar.html#toolButtonStyle-prop) is really very similar to a menu, except that instead of text items in a dropdown, you have [QToolButton](https://doc.qt.io/qt-6/qtoolbutton.html) items in a layout.  

> Is it possible to specify button type (e.g., qtpy.QtWidgets.QRadioButton, napari._qt.widgets.qt_mode_buttons.QtModeRadioButton etc) for actions inside a QModelToolBar?

While it's true that you can [add any generic widgets](https://doc.qt.io/qt-6/qtoolbar.html#addWidget) (in the case where a `QToolButton` isn't appropriate), I would definitely encourage you to take this opportunity to reconsider whether things like `napari._qt.widgets.qt_mode_buttons.QtModeRadioButton` were really the best way to design those layer controls (or whether it was just the "first" way it was designed 😄)

At the moment, being largely declarative, app-model doesn't provide an `Action`-based API for declaring a specific widget instance that would be passed to [`QToolbar.addWidget`](https://doc.qt.io/qt-6/qtoolbar.html#addWidget), so you would have to do that by just directly accessing the `QModelToolBar` and calling `addWidget` on it.

An alternative would be to stick with QToolButtons and action that, when triggered, sets the mode in some context.  And then all of the buttons would have their `toggled` field set as an expression that evaluated to true when their mode was active.  (The benefit of that approach, by the way, is that those buttons would respond to a much broader variety of ways to change the mode.  For example: they would more naturally respond to keybindings that set the mode, or any general programmatic thing that updates that mode in the context somehow).  If possible (and I'm not sure up front whether it is), I'd see if you can design away this whole module: https://github.com/napari/napari/blob/2e9b117a80a43af144457c83f599ffa5bae684a7/napari/_qt/widgets/qt_mode_buttons.py
I would try to play with some examples of QToolBar and QToolButton (with layer mode buttons in mind) and see if you can get a behavior you like.  I suspect the current pattern was used mostly without knowing about the existence of QToolButton

**Comment by lucyleeow** [comment]
Thanks for your input. Did not want to make any potentially controversial changes to `napari` layout but will look into your suggestions.

I'll close this issue.
