### ISSUE TITLE
NOTE: app model v0.3.0 

### ISSUE THREAD

**Issue by tlambert03** [pyapp-kit/app-model#50]
just a note here to remind us that napari https://github.com/napari/napari/pull/4784 pins app-model to <0.3.0.  The intention is that bumping past 0.3.0 indicates dropping support for napari v0.4.17

**Comment by tlambert03** [comment]
@Czaki, what was your idea/plan for changing this as we go forward?  app-model's versioning is constrained a bit unconventionally here (i.e. not semantic versioning) in deference to napari versioning.    Let me know if it's been long enough now and if you're comfortable with me managing the version here independently of napari (similarly to how napari handles all its other dependencies).  If you have thoughts in general, it would be good to check in again now that this issue is a year and a half old

**Comment by Czaki** [comment]
I do not understand. 
When You introduce app-model, you claim that it is early phase so it may require breaking changes in the future. So I suggest that when you introduce breaking changes, you will release 0.3.0 and we could test if it somehow breaks napari from main, and if not, then bump constraints, otherwise introduce bug fixes and bump constraints.

The main reason to put constraints is to not break new installation from pip/conda, not to block app-model development. 


> app-model's versioning is constrained a bit unconventionally here (i.e. not semantic versioning) in deference to napari versioning.

You mean that current waiting on napari block semantic versioning, or you do not want to follow semantic versioning? 


> similarly to how napari handles all its other dependencies

We currently assume that dependencies will follow semantic versioning and for fragile one put upper constraint to manual validate if everything works.

**Comment by tlambert03** [comment]
I mean I’d like to follow semantic versioning.  But I have this note here that says I can’t bump to v0.3 without checking in with napari essentially… and that’s not semantic (the semantics are linked to napari, rather than to the changes)

**Comment by tlambert03** [comment]
Sounds like you’re fine with me closing this issue though and just using semantic versioning as usual?  As you know, I test napari regularly here and won’t make any breaking changes that break napari tests without depreciation

**Comment by Czaki** [comment]
Yes.

**Comment by tlambert03** [comment]
thanks

**Comment by Czaki** [comment]
#171 shows that tests are incomplete.

**Comment by tlambert03** [comment]
ok, feel free to update tests here to cover it.  For what it's worth, that series of discussion went for a couple months without any feedback from napari side.
